spring:
  application:
    name: profile
  config:
    activate:
      on-profile: default
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/profile
    username: profile
    password: profile1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
server:
  port: 8080

jwt:
  secretKey: adsfadgaerhsfvnbsfgjerstyjgfdhsfhsdrhsdfhadsfadgaerhsfvnbsfgjerstyjgfdhsfhsdrhsdfh
  expiration: 43200000
  refreshExpiration: 604800000


